# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

limit = 4000000

first, second = 1, 1
fibo = 0
sum = 0;

while first + second < limit:
    fibo = first + second
    first = second
    second = fibo
    if fibo % 2 == 0:
        sum += fibo

print(sum)
